name: "Build and test"
on:
  pull_request:
  push:
    branches: [master]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: git checkout
      uses: actions/checkout@v2.4.0
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main
    - name: configure cachix
      uses: cachix/cachix-action@v10
      with:
        name: ranfdev-geopard
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: run checks
      run: nix --print-build-logs flake check
    - name: build
      run: nix --print-build-logs build
